import { create } from "zustand";

export type Language = "fr" | "en";

export const translations = {
  fr: {
    // Login Screen
    supervisionPlatform: "Plateforme de Supervision",
    clearMode: "Mode clair",
    darkMode: "Mode sombre",
    securitySuite: "Security Suite",
    brandingDescription: "Supervision centralisée et performante. Pilotez vos flux vidéo en direct, contrôlez les accès physiques et traitez les alertes de sécurité depuis une console unifiée, simple et efficace.",
    surveillance: "Surveillance",
    surveillanceDesc: "Flux vidéo en temps réel à faible latence.",
    access: "Accès",
    accessDesc: "Contrôle à distance des portes et lecteurs.",
    alerts: "Alertes",
    alertsDesc: "Notifications instantanées des anomalies.",
    authTitle: "Authentification",
    authDesc: "Veuillez renseigner vos identifiants.",
    activeService: "Service actif",
    inactiveService: "Service inactif",
    checkingService: "Vérification...",
    serverUrlLabel: "Adresse du serveur",
    usernameLabel: "Identifiant",
    usernamePlaceholder: "Nom d'utilisateur",
    passwordLabel: "Mot de passe",
    passwordPlaceholder: "••••••••••••",
    submitting: "Validation en cours...",
    loginButton: "Se connecter",
    authFooter: "Console réservée au personnel autorisé",
    errorInvalidPasswordLength: "Longueur de mot de passe invalide (minimum 4 caractères).",
    errorInvalidIdentifierFormat: "Format d'identifiant invalide (minimum 3 caractères).",
    errorInvalidCredentials: "Nom d'utilisateur ou mot de passe incorrect.",
    errorInternalServer: "Erreur interne du serveur.",
    errorConnectionFailed: "Impossible de se connecter à la passerelle de sécurité.",
    
    // Dashboard Navigation & Shell
    dashboardTitle: "Supervision",
    overviewTab: "Vue d’ensemble",
    liveTab: "Surveillance",
    accessTab: "Accès",
    alertsTab: "Alertes",
    eventsTab: "Événements",
    mapTab: "Carte",
    themeToggleLight: "Thème Clair",
    themeToggleDark: "Thème Sombre",
    themeToggleLightLabel: "Thème Clair",
    themeToggleDarkLabel: "Thème Sombre",
    logoutButton: "Déconnexion",
    headerSubtitle: "Console de supervision Wardis",
    systemStable: "Système stable",
    activeAlertsCount: "{{count}} alerte(s)",
    lastActivity: "Dernière activité :",
    operatorId: "ID OP: {{id}}",
    
    // Dashboard Content & Status Panel
    activeCameras: "Caméras actives",
    camerasSynced: "flux vidéo synchronisés",
    doors: "Portes",
    doorsStatusDesc: "ouvertes / configurées",
    activeAlerts: "Alertes actives",
    alertsPriority: "à acquitter en priorité",
    serviceStatus: "État des services",
    latency: "Latence: {{latency}}ms",
    generalStatus: "État général du système",
    statusStable: "stable",
    natsServer: "Serveur NATS",
    natsConnected: "connecté",
    accessGateway: "Passerelle d'accès",
    gatewayOnline: "en ligne",
    videoServer: "Serveur d'enregistrement vidéo",
    serverActive: "actif",
    systemJournal: "Journal système",
    
    // Log items / events
    dashboardReady: "Tableau de bord prêt",
    accessSystemReady: "Système d’accès prêt et à l’écoute",
    videoSyncOk: "Synchronisation vidéo OK",
    intrusionZonesArmed: "Zones d’intrusion armées",
    eventStreamStable: "Flux d’événements stable",
    noCriticalAlerts: "Aucune alerte critique détectée",
    tabLogged: "Onglet : {{label}}",

    // Workspace & Tasks
    taskMenuTitle: "Espace de travail",
    taskMenuDesc: "Ouvrir une nouvelle tâche de supervision",
    taskOverview: "Vue d’ensemble",
    taskLive: "Surveillance vidéo",
    taskAccess: "Contrôle d'accès",
    taskAlarms: "Centre d'alertes",
    taskEvents: "Journal d'événements",
    taskMap: "Carte interactive",
    taskUsers: "Droits & Utilisateurs",
    taskSettings: "Mon Profil",
    taskDiagnostics: "Diagnostics Système",
    taskCameraConfig: "Configuration Caméras",
    taskReports: "Rapports",
    taskAdmin: "Administration & Système",
    taskInvestigation: "Investigation / Lecture",

    // User Settings / Operator Profile
    userSettingsTitle: "Paramètres de l'opérateur",
    accountInfo: "Informations de session",
    changePasswordTitle: "Sécurité & Authentification",
    currentPassword: "Mot de passe actuel",
    newPassword: "Nouveau mot de passe",
    confirmPassword: "Confirmer le nouveau mot de passe",
    updatePasswordBtn: "Mettre à jour le mot de passe",
    passwordSuccess: "Mot de passe modifié avec succès !",
    passwordError: "Le mot de passe actuel est incorrect ou invalide.",
    passwordMismatch: "Les nouveaux mots de passe ne correspondent pas.",
    passwordLengthErr: "Le nouveau mot de passe doit comporter au moins 4 caractères.",
    themeLabel: "Thème graphique",
    languageLabel: "Langue de l'interface",

    // User Administration & RBAC
    userAdminTitle: "Gestion des Comptes & Privilèges",
    createUserTitle: "Créer un nouvel utilisateur",
    userListTitle: "Utilisateurs système",
    emailOrUsernameLabel: "Identifiant / E-mail",
    roleLabel: "Rôle assigné",
    statusLabel: "Statut du compte",
    actionsLabel: "Actions",
    statusActive: "ACTIF",
    statusSuspended: "SUSPENDU",
    userCreatedSuccess: "Utilisateur créé avec succès !",
    userDeleteConfirm: "Êtes-vous sûr de vouloir supprimer cet utilisateur ? Cette action est irréversible.",
    userDeletedSuccess: "Utilisateur supprimé avec succès.",
    saveRightsBtn: "Enregistrer les privilèges",
    rightsSavedSuccess: "Privilèges mis à jour avec succès !",
    rightsSavedError: "Erreur lors de la mise à jour des privilèges.",
    permissionsMatrixTitle: "Privilèges Système par Rôle",
    userEntityPermissionsTitle: "Sécurité fine (Caméras & Portes)",
    permissionViewLive: "Visualiser Direct",
    permissionViewArchive: "Consulter Archives",
    permissionUnlockDoor: "Ouvrir les portes",
    permissionManageUsers: "Administrer Comptes",
    roleAdmin: "Administrateur",
    roleSupervisor: "Superviseur",
    roleOperator: "Opérateur",
    roleGuest: "Invité (Lecture seule)",
    roleGuard: "Gardien de Sécurité",
    mfaTitle: "Double Facteur (2FA)",
    mfaSetupDesc: "Scannez ce QR Code avec votre application d'authentification (Google Authenticator) ou copiez la clé secrète.",
    mfaVerifyCodeLabel: "Code de vérification",
    mfaVerifyCodePlaceholder: "Ex: 123456",
    mfaEnableBtn: "Activer le double facteur",
    mfaDisableBtn: "Désactiver le double facteur",
    mfaStatusActive: "Le double facteur est activé sur votre compte.",
    mfaStatusInactive: "Le double facteur n'est pas activé.",
    mfaCodeErr: "Code de vérification invalide.",
    mfaTokenExpiredErr: "La session d'authentification a expiré.",
    mfaRequiredTitle: "Authentification à double facteur",
    mfaRequiredDesc: "Saisissez le code à 6 chiffres généré par votre application.",
    mfaRequiredButton: "Vérifier le code",
    mfaCancelButton: "Retour",
    auditLogTab: "Journal d'Audit",
    activeSessionsTab: "Sessions Actives",
    customRolesTab: "Rôles Système",
    auditTime: "Date & Heure",
    auditUser: "Opérateur",
    auditAction: "Action",
    auditResource: "Ressource",
    auditIP: "Adresse IP",
    auditStatus: "Statut",
    auditDetails: "Détails",
    sessionIP: "Adresse IP",
    sessionUA: "Navigateur / Client",
    sessionCreated: "Connexion",
    sessionExpires: "Expiration",
    sessionRevokeBtn: "Déconnecter",
    sessionRevokeConfirm: "Êtes-vous sûr de vouloir forcer la déconnexion de cette session ?",
    rolePermissionsTitle: "Permissions associées au rôle",
    createRoleBtn: "Créer le rôle",
    deleteRoleConfirm: "Supprimer ce rôle ?"
  },
  en: {
    // Login Screen
    supervisionPlatform: "Supervision Platform",
    clearMode: "Light mode",
    darkMode: "Dark mode",
    securitySuite: "Security Suite",
    brandingDescription: "Centralized and powerful supervision. Stream live video, control physical access, and process security alerts from a unified, simple, and efficient console.",
    surveillance: "Surveillance",
    surveillanceDesc: "Real-time video streams with low latency.",
    access: "Access",
    accessDesc: "Remote control of doors and readers.",
    alerts: "Alerts",
    alertsDesc: "Instant notifications of anomalies.",
    authTitle: "Authentication",
    authDesc: "Please enter your credentials.",
    activeService: "Service active",
    inactiveService: "Service inactive",
    checkingService: "Checking...",
    serverUrlLabel: "Server address",
    usernameLabel: "Username",
    usernamePlaceholder: "Username",
    passwordLabel: "Password",
    passwordPlaceholder: "••••••••••••",
    submitting: "Validating...",
    loginButton: "Sign in",
    authFooter: "Console reserved for authorized personnel",
    errorInvalidPasswordLength: "Invalid password length (minimum 4 characters).",
    errorInvalidIdentifierFormat: "Invalid identifier format (minimum 3 characters).",
    errorInvalidCredentials: "Invalid username or password.",
    errorInternalServer: "Internal server error.",
    errorConnectionFailed: "Failed to connect to the security gateway.",
    
    // Dashboard Navigation & Shell
    dashboardTitle: "Supervision",
    overviewTab: "Overview",
    liveTab: "Surveillance",
    accessTab: "Access",
    alertsTab: "Alerts",
    eventsTab: "Events",
    mapTab: "Map",
    themeToggleLight: "Light Theme",
    themeToggleDark: "Dark Theme",
    themeToggleLightLabel: "Light Theme",
    themeToggleDarkLabel: "Dark Theme",
    logoutButton: "Sign Out",
    headerSubtitle: "Wardis supervision console",
    systemStable: "System stable",
    activeAlertsCount: "{{count}} alert(s)",
    lastActivity: "Last activity:",
    operatorId: "OP ID: {{id}}",
    
    // Dashboard Content & Status Panel
    activeCameras: "Active cameras",
    camerasSynced: "video streams synced",
    doors: "Doors",
    doorsStatusDesc: "open / configured",
    activeAlerts: "Active alerts",
    alertsPriority: "to acknowledge first",
    serviceStatus: "Service status",
    latency: "Latency: {{latency}}ms",
    generalStatus: "General system status",
    statusStable: "stable",
    natsServer: "NATS Server",
    natsConnected: "connected",
    accessGateway: "Access Gateway",
    gatewayOnline: "online",
    videoServer: "Video recording server",
    serverActive: "active",
    systemJournal: "System journal",
    
    // Log items / events
    dashboardReady: "Dashboard ready",
    accessSystemReady: "Access system ready and listening",
    videoSyncOk: "Video sync OK",
    intrusionZonesArmed: "Intrusion zones armed",
    eventStreamStable: "Event stream stable",
    noCriticalAlerts: "No critical alerts detected",
    tabLogged: "Tab: {{label}}",

    // Workspace & Tasks
    taskMenuTitle: "Workspace Tasks",
    taskMenuDesc: "Open a new supervision task tab",
    taskOverview: "Overview",
    taskLive: "Video Surveillance",
    taskAccess: "Access Control",
    taskAlarms: "Alerts Center",
    taskEvents: "Event Journal",
    taskMap: "Interactive Map",
    taskUsers: "Users & Rights",
    taskSettings: "My Profile",
    taskDiagnostics: "System Diagnostics",
    taskCameraConfig: "Camera Configuration",
    taskReports: "Reports",
    taskAdmin: "Administration & System",
    taskInvestigation: "Investigation / Playback",

    // User Settings / Operator Profile
    userSettingsTitle: "Operator Settings",
    accountInfo: "Session Information",
    changePasswordTitle: "Security & Authentication",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmPassword: "Confirm New Password",
    updatePasswordBtn: "Update Password",
    passwordSuccess: "Password updated successfully!",
    passwordError: "Current password is wrong or invalid.",
    passwordMismatch: "New passwords do not match.",
    passwordLengthErr: "New password must be at least 4 characters long.",
    themeLabel: "Display Theme",
    languageLabel: "System Language",

    // User Administration & RBAC
    userAdminTitle: "User Accounts & Rights Management",
    createUserTitle: "Create new user",
    userListTitle: "System Users",
    emailOrUsernameLabel: "Identifier / Email",
    roleLabel: "Assigned Role",
    statusLabel: "Account Status",
    actionsLabel: "Actions",
    statusActive: "ACTIVE",
    statusSuspended: "SUSPENDED",
    userCreatedSuccess: "User created successfully!",
    userDeleteConfirm: "Are you sure you want to delete this user? This action cannot be undone.",
    userDeletedSuccess: "User deleted successfully.",
    saveRightsBtn: "Save Privileges",
    rightsSavedSuccess: "Privileges updated successfully!",
    rightsSavedError: "Failed to update privileges.",
    permissionsMatrixTitle: "System Privileges per Role",
    userEntityPermissionsTitle: "Fine-grained Security (Cameras & Doors)",
    permissionViewLive: "View Live",
    permissionViewArchive: "View Archive",
    permissionUnlockDoor: "Unlock Doors",
    permissionManageUsers: "Administer Accounts",
    roleAdmin: "Administrator",
    roleSupervisor: "Supervisor",
    roleOperator: "Operator",
    roleGuest: "Guest (Read-only)",
    roleGuard: "Security Guard",
    mfaTitle: "Two-Factor Auth (2FA)",
    mfaSetupDesc: "Scan this QR Code with your authenticator app (Google Authenticator) or copy the secret key.",
    mfaVerifyCodeLabel: "Verification code",
    mfaVerifyCodePlaceholder: "E.g., 123456",
    mfaEnableBtn: "Enable Two-Factor Auth",
    mfaDisableBtn: "Disable Two-Factor Auth",
    mfaStatusActive: "Two-factor authentication is enabled on your account.",
    mfaStatusInactive: "Two-factor authentication is disabled.",
    mfaCodeErr: "Invalid verification code.",
    mfaTokenExpiredErr: "Authentication session has expired.",
    mfaRequiredTitle: "Two-Factor Authentication",
    mfaRequiredDesc: "Enter the 6-digit code generated by your app.",
    mfaRequiredButton: "Verify code",
    mfaCancelButton: "Cancel",
    auditLogTab: "Audit Log",
    activeSessionsTab: "Active Sessions",
    customRolesTab: "System Roles",
    auditTime: "Date & Time",
    auditUser: "Operator",
    auditAction: "Action",
    auditResource: "Resource",
    auditIP: "IP Address",
    auditStatus: "Status",
    auditDetails: "Details",
    sessionIP: "IP Address",
    sessionUA: "Browser / Client",
    sessionCreated: "Login Time",
    sessionExpires: "Expires",
    sessionRevokeBtn: "Disconnect",
    sessionRevokeConfirm: "Are you sure you want to force logout this session?",
    rolePermissionsTitle: "Role Permissions Matrix",
    createRoleBtn: "Create Role",
    deleteRoleConfirm: "Delete this role?"
  }
};

export type TranslationKey = keyof typeof translations.fr;

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey, variables?: Record<string, string | number>) => string;
}

export const useLanguageStore = create<LanguageState>((set, get) => ({
  language: (typeof window !== "undefined" ? localStorage.getItem("wardis-lang") as Language : "fr") || "fr",
  setLanguage: (lang) => {
    if (typeof window !== "undefined") {
      localStorage.setItem("wardis-lang", lang);
    }
    set({ language: lang });
  },
  t: (key, variables) => {
    const lang = get().language;
    let translation = translations[lang][key] || translations["fr"][key] || String(key);
    if (variables) {
      Object.entries(variables).forEach(([k, v]) => {
        translation = translation.replace(new RegExp(`{{${k}}}`, "g"), String(v));
      });
    }
    return translation;
  }
}));
